name: build-rtcqs

description: Build and release rtcqs

on: [push]

env:
  WORKDIR: /home/forgejo/rtcqs
  PROJECT_NAME: rtcqs
  
jobs:
  build-rtcqs:
    runs-on: docker
    container:
      image: node:20-bookworm
      options: "--workdir ${{ env.WORKDIR }}"
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          tzdata apt-utils build-essential \
          python3-dev python-is-python3 python3-pip \
          python3-venv && \
          apt-get dist-upgrade -y && \
          apt-get clean && \
          rm -rf /var/lib/apt/lists/* && \
          ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime && \
          dpkg-reconfigure -f noninteractive tzdata
      - run: |
          python3 -m venv venv && \
          venv/bin/pip install --upgrade pyinstaller && \
          venv/bin/pyinstaller --onefile src/rtcqs/rtcqs.py && \
          venv/bin/pyinstaller --onefile --windowed src/rtcqs/rtcqs_gui.py
        

  release-rtcqs:
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - uses: actions/forgejo-release@v1
        with:
          direction: upload
          url: https://codeberg.org
          token: ${{ secrets.CODEBERG_TOKEN }}
          release-dir: dist/

