name: build-rtcqs

description: Build and release rtcqs

on: [push]

jobs:
  build-rtcqs:
    runs-on: docker
    container:
      image: node:20-bookworm
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          tzdata apt-utils build-essential \
          python3-dev python-is-python3 python3-pip \
          python3-venv python3-tk && \
          apt-get dist-upgrade -y && \
          apt-get clean && \
          rm -rf /var/lib/apt/lists/* && \
          ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime && \
          dpkg-reconfigure -f noninteractive tzdata
      - run: |
          python3 -m venv venv && \
          venv/bin/pip install --upgrade pysimplegui==4.60.5 pyinstaller && \
          venv/bin/pyinstaller --onefile src/rtcqs/rtcqs.py && \
          venv/bin/pyinstaller --onefile --windowed src/rtcqs/rtcqs_gui.py
      - uses: actions/upload-artifact@v3
        with:
          name: rtcqs
          path: dist/rtcqs
      - uses: actions/upload-artifact@v3
        with:
          name: rtcqs_gui
          path: dist/rtcqs_gui
      - uses: actions/forgejo-release@v1
        with:
          direction: upload
          token: ${{ secrets.CODEBERG_TOKEN }}
          release-dir: dist/
          verbose: true
          tag: v0.6.2
          override: true
